# Generated by Django 6.0.6 on 2026-07-09 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_expo_push_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, choices=[('almaty', 'Алматы'), ('astana', 'Астана'), ('shymkent', 'Шымкент'), ('karaganda', 'Қарағанды'), ('aktobe', 'Ақтөбе'), ('taraz', 'Тараз'), ('pavlodar', 'Павлодар'), ('ust_kamenogorsk', 'Өскемен'), ('semey', 'Семей'), ('atyrau', 'Атырау'), ('kostanay', 'Қостанай'), ('kyzylorda', 'Қызылорда'), ('uralsk', 'Орал'), ('petropavlovsk', 'Петропавл'), ('aktau', 'Ақтау'), ('temirtau', 'Теміртау'), ('turkestan', 'Түркістан'), ('taldykorgan', 'Талдықорған'), ('ekibastuz', 'Екібастұз'), ('rudny', 'Рудный')], default='', max_length=50),
        ),
    ]
