# Generated by Django 6.0.6 on 2026-08-11 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_backfill_businessclient_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='base_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]