# Generated by Django 6.0.6 on 2026-08-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_base_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bonus_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bonus_sales_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]