# Generated by Django 6.0.6 on 2026-08-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_bonus_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=10),
        ),
    ]