# Generated by Django 6.0.6 on 2026-06-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_productrequest_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrequest',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='productrequest',
            name='delivery_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productrequest',
            name='desired_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
