# Generated by Django 6.0.6 on 2026-06-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('food_beverages', 'Продукты и напитки'), ('electronics', 'Электроника'), ('clothing', 'Одежда и обувь'), ('construction', 'Строительные материалы'), ('chemicals', 'Химия и бытовая химия'), ('furniture', 'Мебель'), ('automotive', 'Автозапчасти'), ('office', 'Офисные товары'), ('medical', 'Медицинские товары'), ('agriculture', 'Сельское хозяйство'), ('packaging', 'Упаковка'), ('equipment', 'Оборудование и инструменты'), ('cosmetics', 'Косметика и гигиена'), ('textile', 'Ткани и текстиль'), ('other', 'Другое')], default='other', max_length=50),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
