# Generated by Django 6.0.6 on 2026-07-28 09:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_category_delete_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='city',
            field=models.CharField(choices=[('almaty', 'Алматы'), ('astana', 'Астана'), ('shymkent', 'Шымкент'), ('karaganda', 'Қарағанды'), ('aktobe', 'Ақтөбе'), ('taraz', 'Тараз'), ('pavlodar', 'Павлодар'), ('ust_kamenogorsk', 'Өскемен'), ('semey', 'Семей'), ('atyrau', 'Атырау'), ('kostanay', 'Қостанай'), ('kyzylorda', 'Қызылорда'), ('uralsk', 'Орал'), ('petropavlovsk', 'Петропавл'), ('aktau', 'Ақтау'), ('temirtau', 'Теміртау'), ('turkestan', 'Түркістан'), ('taldykorgan', 'Талдықорған'), ('ekibastuz', 'Екібастұз'), ('rudny', 'Рудный')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['supplier', 'city'], name='catalog_pro_supplie_eb5595_idx'),
        ),
    ]