# Generated by Django 6.0.6 on 2026-08-11 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_backfill_product_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='What this unit actually costs the supplier — used to compute profit margin. Optional; treated as 0 if unset.', max_digits=10, null=True),
        ),
    ]