# Generated by Django 6.0.6 on 2026-08-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_order_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]