# Generated by Django 6.0.6 on 2026-07-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_requests', '0005_productrequest_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrequest',
            name='city',
            field=models.CharField(blank=True, choices=[('almaty', 'Алматы'), ('astana', 'Астана'), ('shymkent', 'Шымкент'), ('karaganda', 'Қарағанды'), ('aktobe', 'Ақтөбе'), ('taraz', 'Тараз'), ('pavlodar', 'Павлодар'), ('ust_kamenogorsk', 'Өскемен'), ('semey', 'Семей'), ('atyrau', 'Атырау'), ('kostanay', 'Қостанай'), ('kyzylorda', 'Қызылорда'), ('uralsk', 'Орал'), ('petropavlovsk', 'Петропавл'), ('aktau', 'Ақтау'), ('temirtau', 'Теміртау'), ('turkestan', 'Түркістан'), ('taldykorgan', 'Талдықорған'), ('ekibastuz', 'Екібастұз'), ('rudny', 'Рудный')], default='', max_length=50),
            preserve_default=False,
        ),
    ]