# Generated by Django 6.0.6 on 2026-08-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_request', 'New Request'), ('request_accepted', 'Request Accepted'), ('request_declined', 'Request Declined'), ('request_fulfilled', 'Request Fulfilled'), ('request_cancelled', 'Request Cancelled'), ('new_response', 'New Response')], max_length=30),
        ),
    ]